Repository Team-ElderCare/ElderCare-Android, pull requests merged in 2025-02, with the labels that each got.

#45 [Add/#27] 기본 정보 등록 데이터 클래스 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/eldercare/presentation/model/BasicInfoModel.kt
  app/src/main/java/com/example/eldercare/presentation/model/DummyModel.kt
  app/src/main/java/com/example/eldercare/presentation/ui/activity/ContactAdapter.kt
  app/src/main/java/com/example/eldercare/presentation/ui/activity/RunFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/custom/CustomButton.kt
  app/src/main/java/com/example/eldercare/presentation/ui/custom/CustomEditText.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_run.xml
  app/src/main/res/layout/fragment_tool.xml
  app/src/main/res/layout/item_additional_contact.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/layout/view_custom_edit_text.xml
  app/src/main/res/values/strings.xml
Labels: ADD➕

#54 [Feat/#50] 기본 정보 등록(보호자 & 보호 대상자) UI 및 백엔드 로직 구현
  app/src/main/java/com/example/eldercare/data/api/ProtectedApi.kt
  app/src/main/java/com/example/eldercare/data/api/UserApi.kt
  app/src/main/java/com/example/eldercare/data/datasource/remote/basicInfo/BasicInfoDataSource.kt
  app/src/main/java/com/example/eldercare/data/model/request/ProtectedRegistrationRequest.kt
  app/src/main/java/com/example/eldercare/data/model/request/UserRegistrationRequest.kt
  app/src/main/java/com/example/eldercare/data/repository/basicInfo/BasicInfoRepositoryImpl.kt
  app/src/main/java/com/example/eldercare/di/ApiModule.kt
  app/src/main/java/com/example/eldercare/di/RepositoryModule.kt
  app/src/main/java/com/example/eldercare/domain/model/basicInfo/Address.kt
  app/src/main/java/com/example/eldercare/domain/model/basicInfo/Relationship.kt
  app/src/main/java/com/example/eldercare/domain/repository/BasicInfoRepository.kt
  app/src/main/java/com/example/eldercare/domain/usecase/proTected/PostProtectedRegistrationUseCase.kt
  app/src/main/java/com/example/eldercare/domain/usecase/user/PostUserRegistrationUseCase.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/BasicInfoActivity.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/BasicInfoStep.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/BasicInfoViewModel.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/guardian/GuardianNameFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/guardian/GuardianPhoneFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/guardian/GuardianPhotoFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/guardian/GuardianRelationshipFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/protectedPerson/ProtectedAddressFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/protectedPerson/ProtectedBirthFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/protectedPerson/ProtectedEmergencyContactFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/protectedPerson/ProtectedNameFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/protectedPerson/ProtectedNicknameFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/basicInfo/protectedPerson/ProtectedPhoneFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/custom/CustomEditText.kt
  app/src/main/res/color/selector_chip_fill_relation_background.xml
  app/src/main/res/color/selector_chip_fill_relation_text_color.xml
  app/src/main/res/drawable/ic_plus_24dp.xml
  app/src/main/res/layout/activity_basic_info.xml
  app/src/main/res/layout/fragment_info_guardian_name.xml
  app/src/main/res/layout/fragment_info_guardian_phone.xml
  app/src/main/res/layout/fragment_info_guardian_photo.xml
  app/src/main/res/layout/fragment_info_guardian_relationship.xml
  app/src/main/res/layout/fragment_info_protected_person_address.xml
  app/src/main/res/layout/fragment_info_protected_person_birth.xml
  app/src/main/res/layout/fragment_info_protected_person_emergency_contact.xml
  app/src/main/res/layout/fragment_info_protected_person_name.xml
  app/src/main/res/layout/fragment_info_protected_person_nickname.xml
  app/src/main/res/layout/fragment_info_protected_person_phone.xml
  app/src/main/res/layout/view_custom_edit_text.xml
  app/src/main/res/navigation/basic_info_nav_graph.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: FEAT✨, ☀️정범☀️

#55 Feat#36 home UI
  app/build.gradle.kts
  app/src/main/java/com/example/eldercare/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/example/eldercare/presentation/ui/home/adapter/UserRecentActivityRVAdapter.kt
  app/src/main/res/drawable/background_activity.xml
  app/src/main/res/drawable/ic_green_circle_16dp.xml
  app/src/main/res/drawable/ic_plus_20dp.xml
  app/src/main/res/drawable/ic_red_circle_16dp.xml
  app/src/main/res/drawable/ic_yellow_circle_16dp.xml
  app/src/main/res/drawable/rectangle_white_radius_16_without_stroke.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_add_alarm_button.xml
  app/src/main/res/layout/item_danger.xml
  app/src/main/res/layout/item_sensed.xml
  app/src/main/res/layout/layout_custom_tool_tip.xml
  app/src/main/res/layout/view_drug_alarm.xml
  app/src/main/res/layout/view_empty_drug_alarm.xml
  app/src/main/res/layout/view_recent_activity.xml
Labels: FEAT✨, ⭐성현⭐
