Repository Team-ElderCare/ElderCare-Android, pull requests merged in 2025-01, with the labels that each got.

#16 [Mod] 컬러, 폰트, spacing 수정
  README.md
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-v26/type.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/text_appearance.xml
  app/src/main/res/values/type.xml
Labels: MOD✅, 🐸성민🐸

#19 [add/#18]: icon 추가
  app/src/main/res/drawable/ic_activity_25dp.xml
  app/src/main/res/drawable/ic_alert_circle.xml
  app/src/main/res/drawable/ic_alert_triangle.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_default_profile_80dp.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_edit_25dp.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_home_25dp.xml
  app/src/main/res/drawable/ic_hub.xml
  app/src/main/res/drawable/ic_log_out.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_profile_large_100dp.xml
  app/src/main/res/drawable/ic_run.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_settings_25dp.xml
  app/src/main/res/drawable/ic_state_active.xml
  app/src/main/res/drawable/ic_state_default.xml
  app/src/main/res/drawable/ic_tool_25dp.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/ic_wifi.xml
  app/src/main/res/drawable/ic_wifi_off.xml
Labels: INIT, ⭐성현⭐, ADD➕

#24 Add/#12 공통 버튼 컴포넌트 추가
  app/src/main/res/color/selector_capsule_btn_color.xml
  app/src/main/res/color/selector_square_btn_color.xml
  app/src/main/res/color/selector_square_btn_text_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/themes.xml
Labels: ⛄규현⛄, ADD➕

#31 [ADD/#29] 스플래시 화면 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/eldercare/data/datasource/repository/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/example/eldercare/domain/auth/AuthViewModel.kt
  app/src/main/java/com/example/eldercare/domain/model/UiState.kt
  app/src/main/java/com/example/eldercare/domain/model/UserInfo.kt
  app/src/main/java/com/example/eldercare/domain/repository/AuthRepository.kt
  app/src/main/java/com/example/eldercare/domain/usecase/PostSignInUseCase.kt
  app/src/main/java/com/example/eldercare/presentation/ui/splash/SplashActivity.kt
  app/src/main/java/com/example/eldercare/util/token/AccessTokenManager.kt
  app/src/main/res/drawable/ic_splash_logo_icon.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
  gradlew
Labels: CHORE🎀, FEAT✨, ⛄규현⛄, ADD➕

#34 Add/#33 edit text component
  app/src/main/java/com/example/eldercare/presentation/ui/custoom/CustomEditText.kt
  app/src/main/res/drawable/ic_camera_24dp.xml
  app/src/main/res/drawable/ic_clear_21x20dp.xml
  app/src/main/res/drawable/ic_dropdown_17x15dp.xml
  app/src/main/res/drawable/shape_for_edit_text.xml
  app/src/main/res/drawable/shape_for_edit_text_error.xml
  app/src/main/res/layout/view_custom_edit_text.xml
  app/src/main/res/values/attrs.xml
Labels: ☀️정범☀️, ADD➕

#37 [Mod/#35] PR_Template, DI 모듈, 서버 통신 파일 수정
  .github/workflows/pr_checker.yml
  app/src/main/java/com/example/eldercare/data/api/AuthApi.kt
  app/src/main/java/com/example/eldercare/data/datasource/remote/auth/AuthRemoteDataSource.kt
  app/src/main/java/com/example/eldercare/data/datasource/remote/auth/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/example/eldercare/data/datasource/remote/home/HomeRemoteDataSource.kt
  app/src/main/java/com/example/eldercare/data/datasource/remote/home/HomeRemoteDataSourceImpl.kt
  app/src/main/java/com/example/eldercare/data/datasource/repository/home/HomeRepositoryImpl.kt
  app/src/main/java/com/example/eldercare/data/mapper/TestMapper.kt
  app/src/main/java/com/example/eldercare/data/model/response/DummyResponse.kt
  app/src/main/java/com/example/eldercare/data/repository/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/example/eldercare/data/repository/home/HomeRepositoryImpl.kt
  app/src/main/java/com/example/eldercare/di/ApiModule.kt
  app/src/main/java/com/example/eldercare/di/DataSourceModule.kt
  app/src/main/java/com/example/eldercare/di/DataStoreModule.kt
  app/src/main/java/com/example/eldercare/di/NetworkModule.kt
  app/src/main/java/com/example/eldercare/di/RepositoryModule.kt
  app/src/main/java/com/example/eldercare/di/UseCaseModule.kt
Labels: MOD✅, 🐸성민🐸
